name: Weswoodworth
favicon: null
layout_spectrum: 0.6637315398547798
typography_spectrum: 0.2898686262778938
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7229649445507675
  lightness: 0.7549552079290152
  saturation: 0.29050908354111016
  rhythmicContrast: 0.45900846645236015
purpose: []
