name: Weswoodworth
favicon: null
layout_spectrum: 0.9279073621146381
typography_spectrum: 0.5988383279182017
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7008060328662395
  lightness: 0.9888733248226345
  saturation: 0.6539782907348126
  rhythmicContrast: 0.3872127151116729
purpose: []
