name: Weswoodworth
favicon: null
layout_spectrum: 0.0754894579295069
typography_spectrum: 0.5270670305471867
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.8757348598446697
  lightness: 0.4054901390336454
  saturation: 0.7092384195420891
  rhythmicContrast: 0.8457233875524253
purpose: []
