name: Weswoodworth
favicon: null
layout_spectrum: 0.17577131697908044
typography_spectrum: 0.8207053760997951
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.5899133656639606
  lightness: 0.5589642189443111
  saturation: 0.03985012439079583
  rhythmicContrast: 0.16494497493840754
purpose: []
