name: Weswoodworth
favicon: null
layout_spectrum: 0.5724598653614521
typography_spectrum: 0.4398980145342648
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.3724662186577916
  lightness: 0.934077137382701
  saturation: 0.30597946350462735
  rhythmicContrast: 0.2363290146458894
purpose: []
