name: Weswoodworth
favicon: null
layout_spectrum: 0.38943
typography_spectrum: 0.63863
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#91c6f2'
    - '#020607'
    - '#0a65e9'
    - '#d39b2e'
  brandStrength: 0.5625
  lightness: 0.375
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
