name: Weswoodworth
favicon: null
layout_spectrum: 0.49690652219578624
typography_spectrum: 0.04162960289977491
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7700201615225524
  lightness: 0.5784936316777021
  saturation: 0.9846037840470672
  rhythmicContrast: 0.5491968775168061
purpose: []
