name: Weswoodworth
favicon: null
layout_spectrum: 0.8098524566739798
typography_spectrum: 0.45825785608030856
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8637536489404738
  lightness: 0.23076709895394742
  saturation: 0.8939590642694384
  rhythmicContrast: 0.2385635985992849
purpose: []
