name: Weswoodworth
favicon: null
layout_spectrum: 0.6717264256440103
typography_spectrum: 0.4062887094914913
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.15119200479239225
  lightness: 0.7000209286343306
  saturation: 0.3652190580032766
  rhythmicContrast: 0.5652663707733154
purpose: []
