name: Weswoodworth
favicon: null
layout_spectrum: 0.861058889189735
typography_spectrum: 0.10535508813336492
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.23996255989186466
  lightness: 0.8132867810782045
  saturation: 0.09942021942697465
  rhythmicContrast: 0.7641620228532702
purpose: []
