name: Weswoodworth
favicon: null
layout_spectrum: 0.9203436840325594
typography_spectrum: 0.49990195594727993
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8048430560156703
  lightness: 0.9823074131272733
  saturation: 0.7887396321166307
  rhythmicContrast: 0.6788307107053697
purpose: []
