name: Weswoodworth
favicon: null
layout_spectrum: 0.36121790669858456
typography_spectrum: 0.47852256312035024
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.01672544563189149
  lightness: 0.7243706667795777
  saturation: 0.3305923296138644
  rhythmicContrast: 0.9207357291597873
purpose: []
