name: Weswoodworth
favicon: null
layout_spectrum: 0.4543629747349769
typography_spectrum: 0.8000776497647166
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.697740999981761
  lightness: 0.0013761864975094795
  saturation: 0.2887002807110548
  rhythmicContrast: 0.3476726484950632
purpose: []
