name: Weswoodworth
favicon: null
layout_spectrum: 0.048705565044656396
typography_spectrum: 0.9253093227744102
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.17080814554356039
  lightness: 0.41221090336330235
  saturation: 0.1951752349268645
  rhythmicContrast: 0.5508346082642674
purpose: []
