name: Weswoodworth
favicon: null
layout_spectrum: 0.9527544050943106
typography_spectrum: 0.7242224437650293
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8033333946950734
  lightness: 0.44129195320419967
  saturation: 0.8098117739427835
  rhythmicContrast: 0.5837122141383588
purpose: []
