name: Weswoodworth
favicon: null
layout_spectrum: 0.8784655753988773
typography_spectrum: 0.44653021614067256
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.4673339978326112
  lightness: 0.6626412777695805
  saturation: 0.33492046664468944
  rhythmicContrast: 0.08950318372808397
purpose: []
