name: Weswoodworth
favicon: null
layout_spectrum: 0.533230456057936
typography_spectrum: 0.6583583038300276
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.2826198621187359
  lightness: 0.2801447003148496
  saturation: 0.005919429240748286
  rhythmicContrast: 0.9829521968495101
purpose: []
