name: Weswoodworth
favicon: null
layout_spectrum: 0.7276586468797177
typography_spectrum: 0.34460609196685255
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.1607729832176119
  lightness: 0.7842031188774854
  saturation: 0.6390806012786925
  rhythmicContrast: 0.9192426619119942
purpose: []
