name: Weswoodworth
favicon: null
layout_spectrum: 0.8610846698284149
typography_spectrum: 0.6689451055135578
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5989614638965577
  lightness: 0.8591962619684637
  saturation: 0.18049213150516152
  rhythmicContrast: 0.16810121363960207
purpose: []
