name: Weswoodworth
favicon: null
layout_spectrum: 0.6066912151873112
typography_spectrum: 0.26224202127195895
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.03590246243402362
  lightness: 0.8668355869594961
  saturation: 0.4354165671393275
  rhythmicContrast: 0.48032522131688893
purpose: []
