name: Weswoodworth
favicon: null
layout_spectrum: 0.286426595877856
typography_spectrum: 0.9522954938001931
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.1976654587779194
  lightness: 0.14971603825688362
  saturation: 0.5959334492217749
  rhythmicContrast: 0.5072945978026837
purpose: []
