name: Weswoodworth
favicon: null
layout_spectrum: 0.4660953788552433
typography_spectrum: 0.028645024867728353
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.4823343553580344
  lightness: 0.6299672848545015
  saturation: 0.3772400210145861
  rhythmicContrast: 0.2589275611098856
purpose: []
