name: Weswoodworth
favicon: null
layout_spectrum: 0.6568964496254921
typography_spectrum: 0.5402492780704051
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9416591033805162
  lightness: 0.9282181630842388
  saturation: 0.3963207758497447
  rhythmicContrast: 0.15073110861703753
purpose: []
