name: Weswoodworth
favicon: null
layout_spectrum: 0.6980053652077913
typography_spectrum: 0.5755775133147836
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.7091606350149959
  lightness: 0.4990365453995764
  saturation: 0.8529988883528858
  rhythmicContrast: 0.950145531212911
purpose: []
