name: Weswoodworth
favicon: null
layout_spectrum: 0.25758351502008736
typography_spectrum: 0.7103811164852232
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.716268417891115
  lightness: 0.4685244217980653
  saturation: 0.48610310023650527
  rhythmicContrast: 0.6221014210022986
purpose: []
