name: Weswoodworth
favicon: null
layout_spectrum: 0.020038138376548886
typography_spectrum: 0.13201596098951995
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.11073460872285068
  lightness: 0.4615171200130135
  saturation: 0.05829846765846014
  rhythmicContrast: 0.23579995287582278
purpose: []
