name: Weswoodworth
favicon: null
layout_spectrum: 0.526743401074782
typography_spectrum: 0.24116212013177574
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#21212b'
    - '#e4f0e2'
    - '#566c46'
    - '#dc853b'
    - '#99bc67'
  brandStrength: 0.5625
  lightness: 0.375
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
